version: "3.1"

services:
  redis_container:
    image: wit-redis:latest
    container_name: wit-redis
    hostname: localhost
    ports:
      - 6380:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf

    labels:
      - "name=redis"
      - "mode=standalone"

    restart: always
    command: redis-server /usr/local/conf/redis.conf